title: Kayode Omotayo | Data Analyst
logo: 314A0842.jpg
description: Computer Scientist and Data Analytics Consultant with 15+ years of experience across enterprise IT, healthcare technology, cloud computing, and data analytics, with a growing research focus on Artificial Intelligence, Machine Learning, and intelligent decision-support systems.
theme: jekyll-theme-minimal







